### PR TITLE
refactor: Replace dep `wrap-fn` → `wrapped`

### PR DESCRIPTION
**Pull request by Zearin**
This replaces the `wrap-fn` dependency with `wrapped`.  The package `wrapped` was created by the same author as `wrap-fn`, after which [he deprecated `wrap-fn` in favor of `wrapped`](https://github.com/matthewmueller/wrap-fn#readme).

Also, the `Makefile` had hard-coded command-line flags intended for very old versions of Node.js.  This caused the `test` target to fail on newer versions of Node.js.  This PR fixes this issue.

### CODE REVIEW

**Comment by Zearin** [comment]
@ianstormtaylor Can’t figure out the Travis failure on lower versions.  

…On the other hand, I noticed the most recent commit before this PR also failed on lower Travis versions, so perhaps it’s okay.

Sorry to tag you by name on this, but this project looks like it hasn’t been checked on in a while.  I took my best guess at the person to contact.

**Comment by Zearin** [comment]
@nickatsegment @ianstormtaylor Anyone checking these?

**Comment by nickatsegment** [comment]
@dominicbarnes is the latest committer. I'd ask him. But I'm guessing no

**Comment by nickatsegment** [comment]
I'm going to close this just to get it off my PRs list; I'm guessing nobody cares at this point. @Zearin if one of the maintainers shows up they can reopen. Sorry.

**Pull request closed without merging**
